# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: ig.fhir.us-interstate-interoperability
canonical: https://github.com/awatson1978/us-state-profiles
name: US Interstate Interoperability
status: draft
version: 0.6.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: MITRE, Inc
  url: https://github.com/awatson1978/us-state-profiles
dependencies:
  hl7.fhir.us.core: 3.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Legislative Topics: 
    Advanced Directives:  page-advanced-directives.html    
    Medicaid Expansion:  page-medicaid-expansion.html
    Religious Exemptions:  page-religious-exemptions.html
    Medical Cannabis:  page-controlled-substances.html
    Abortion:  page-abortion.html
    In-vitro Fertilization:  page-ivf.html
    Doula Access:  page-doulas.html
    LGBT Foster Care:  page-foster-care.html
    Pediatric Gender Medicine:  page-wpath-at-risk.html
    Trans Sports Participation:  page-trans-sports.html
    Assisted Suicide:  page-assisted-suicide.html
  Location Records:  state-records.html
  Artifacts: artifacts.html
pages:
  index.md:
    title: US State Interoperability Profiles
  profiles.md:
    title: Regional Profiles
  page-advanced-directives.md:
    title: Advanced Directives
  page-foster-care.md:
    title: LGBT Foster Care
  page-trans-sports.md:
    title: Trans Youth Participation in Sports
  page-abortion.md:
    title: Abortion Access
  page-ivf.md:
    title: In-vitro Fertilization (IVF)
  page-assisted-suicide.md:
    title: Assisted Suicide
  page-doulas.md:
    title: Doula Access
  page-controlled-substances.md:
    title: Controlled Substances - Cannabis
  page-religious-exemptions.md:
    title: Religious Exemptions
  page-medicaid-expansion.md:
    title: Medicaid Expansion
  page-wpath-at-risk.md:
    title: Pediatric Gender Medicine
  state-records.md:
    title: Location Records



