# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: mehi.ig.fhir
canonical: http://consent-engine-ig.awatson.mitre.org
name: Consent Engine IG
status: draft
version: 0.3.6
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: MITRE, Inc
  url: https://gitlab.mitre.org/awatson/consent-engine-ig
dependencies:
  hl7.fhir.us.core: 3.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Consent Collection: datacollection.html
  Access Control Lists: consentengine.html
  Regional Profiles: profiles.html
  Distributed Ledgers: blockchain.html
  Artifacts: artifacts.html

pages:
  index.md:
    title: Consent Engine Implementation Guide
  datacollection.md:
    title: Data Collection
  consentengine.md:
    title: Consent Engine
  profiles.md:
    title: Regional Profiles
  blockchain.md:
    title: Distributed Ledgers
