# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: mehi.ig.fhir
canonical: https://gitlab.mitre.org/awatson/us-state-profiles
name: US State Profiles
status: draft
version: 0.4.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: MITRE, Inc
  url: https://gitlab.mitre.org/awatson/us-state-profiles
dependencies:
  hl7.fhir.us.core: 3.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Regional Profiles: 
    Advanced Directives:  page-advanced-directives.html
    Medicaid Expansion:  page-medicaid-expansion.html
    Controlled Substances:  page-controlled-substances.html
    Religious Exemptions:  page-religious-exemptions.html
    Abortion:  page-abortion.html
    Foster Care:  page-foster-care.html
    Trans Sports Participation:  page-trans-sports.html
    WPATH At Risk:  page-wpath-at-risk.html
  Artifacts: artifacts.html
pages:
  index.md:
    title: US State Interoperability Profiles
  profiles.md:
    title: Regional Profiles
  page-advanced-directives.md:
    title: Advanced Directives
  page-foster-care.md:
    title: Foster Care
  page-trans-sports.md:
    title: Trans Sports Participation
  page-abortion.md:
    title: Abortion
  page-controlled-substances.md:
    title: Controlled Substances
  page-religious-exemptions.md:
    title: Religious Exemptions
  page-medicaid-expansion.md:
    title: Medicaid Expansion
  page-wpath-at-risk.md:
    title: WPATH At Risk



