# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: mehi.ig.fhir
canonical: https://gitlab.mitre.org/awatson/us-state-profiles
name: US State Profiles
status: draft
version: 0.3.6
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: MITRE, Inc
  url: https://awatson.pages.mitre.org/us-state-profiles/
dependencies:
  hl7.fhir.us.core: 3.2.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Regional Profiles: profiles.html
  Artifacts: artifacts.html

pages:
  index.md:
    title: US State Profiles Implementation Guide
  profiles.md:
    title: Regional Profiles
